name: Health Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '*/30 * * * *'

jobs:

  build:
    name: From Scratch Test
    runs-on: ubuntu-latest
    steps:

    - name: Prepare
      uses: actions/setup-go@v2
      with:
        go-version: 1.20
      id: go

    - name: Checkout
      uses: actions/checkout@v2

    - name: Unit Test
      run:  |
        GOMAXPROCS=1 go test -v ./... -timeout=2m

    - name: Benchmarck Test
      run:  |
        GOMAXPROCS=1 go test -v ./... -run=^$ -bench=. -benchmem -timeout=2m
